# Generated by Django 2.2.1 on 2019-11-20 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hosts.models
import hosts.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='Hostname')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Updated')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('description', models.TextField(verbose_name='Description')),
                ('createBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), related_name='host_createBy', to=settings.AUTH_USER_MODEL, verbose_name='Create By')),
                ('manageBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), related_name='host_manageBy', to=settings.AUTH_USER_MODEL, verbose_name='Manage By')),
            ],
        ),
        migrations.CreateModel(
            name='OSModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='OS name')),
                ('version', models.CharField(blank=True, max_length=32, null=True, verbose_name='Version Of OS')),
                ('releaseDate', models.DateField(blank=True, null=True, verbose_name='Released Date of OS')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Updated')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('createBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), related_name='os_createBy', to=settings.AUTH_USER_MODEL, verbose_name='Update By')),
                ('updateBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), related_name='os_updateBy', to=settings.AUTH_USER_MODEL, verbose_name='Update By')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ipAddr', models.GenericIPAddressField(unique=True, verbose_name='IP address')),
                ('macAddr', models.CharField(max_length=17, validators=[hosts.validators.validate_mac_address], verbose_name='Mac Address')),
                ('ifName', models.CharField(max_length=16, verbose_name='Interface Name')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Updated')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipAddr', to='hosts.HostModel', verbose_name='Host')),
                ('updateBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), to=settings.AUTH_USER_MODEL, verbose_name='Update By')),
            ],
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host', to='hosts.OSModel', verbose_name='Os system of host'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='services',
            field=models.ManyToManyField(to='services.ServiceModel'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='updateBy',
            field=models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), related_name='host_updateBy', to=settings.AUTH_USER_MODEL, verbose_name='Update By'),
        ),
        migrations.CreateModel(
            name='HostGroupModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name of Host Group')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('description', models.TextField(verbose_name='Description')),
                ('createBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), related_name='host_grp_create_by', to=settings.AUTH_USER_MODEL, verbose_name='Create By')),
                ('hosts', models.ManyToManyField(to='hosts.HostModel')),
                ('manageBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), related_name='host_grp_manage_by', to='auth.Group', verbose_name='Manage By')),
                ('updateBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), related_name='host_grp_update_by', to=settings.AUTH_USER_MODEL, verbose_name='Update By')),
            ],
        ),
    ]
