# Generated by Django 2.2.1 on 2019-05-13 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hosts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=128, verbose_name='Hostname')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('description', models.TextField(verbose_name='Description')),
                ('createBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), related_name='host_create_by', to=settings.AUTH_USER_MODEL, verbose_name='Create By')),
                ('services', models.ManyToManyField(to='services.ServiceModel')),
                ('updateBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), related_name='host_update_by', to=settings.AUTH_USER_MODEL, verbose_name='Update By')),
            ],
        ),
        migrations.CreateModel(
            name='OSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='OS name')),
                ('version', models.CharField(max_length=32, verbose_name='Version Of OS')),
                ('releaseDate', models.DateField(verbose_name='Released Date of OS')),
            ],
        ),
        migrations.CreateModel(
            name='HostOSHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Updated')),
                ('createBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), to=settings.AUTH_USER_MODEL, verbose_name='Update By')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.HostModel', verbose_name='Host')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.OSModel', verbose_name='OS')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroupModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='OS name')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('description', models.TextField(verbose_name='Description')),
                ('createBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), related_name='host_grp_create_by', to=settings.AUTH_USER_MODEL, verbose_name='Create By')),
                ('hosts', models.ManyToManyField(to='hosts.HostModel')),
                ('manageBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), related_name='host_grp_manage_by', to='auth.Group', verbose_name='Manage By')),
                ('updateBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), related_name='host_grp_update_by', to=settings.AUTH_USER_MODEL, verbose_name='Update By')),
            ],
        ),
        migrations.CreateModel(
            name='HostIPHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddr', models.GenericIPAddressField(unique=True)),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('isPrimary', models.BooleanField(default=False, verbose_name='Is Primary Network Card')),
                ('isDisabled', models.BooleanField(default=False, verbose_name='Is Network Card Disabled')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.HostModel', verbose_name='Host')),
                ('updateBy', models.ForeignKey(on_delete=models.SET(hosts.models.get_first_superuser), to=settings.AUTH_USER_MODEL, verbose_name='Update By')),
            ],
            options={
                'unique_together': {('host', 'isPrimary')},
            },
        ),
    ]
