# Generated by Django 2.2.1 on 2019-11-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkcard',
            name='isInUse',
            field=models.BooleanField(default=False, verbose_name='Interface in using'),
        ),
        migrations.AddField(
            model_name='networkcard',
            name='isUp',
            field=models.BooleanField(default=False, verbose_name='Status of Interface'),
        ),
    ]
