# Generated by Django 2.2.1 on 2019-05-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20190513_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmodel',
            name='releaseDate',
            field=models.DateField(blank=True, null=True, verbose_name='Released Date of OS'),
        ),
        migrations.AlterField(
            model_name='osmodel',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Version Of OS'),
        ),
    ]
