# Generated by Django 2.2.1 on 2019-11-20 10:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import re
import services.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Service Name')),
                ('port', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('createBy', models.ForeignKey(on_delete=models.SET(services.models.get_first_superuser), related_name='srv_create_by', to=settings.AUTH_USER_MODEL, verbose_name='Create By')),
                ('updateBy', models.ForeignKey(on_delete=models.SET(services.models.get_first_superuser), related_name='srv_update_by', to=settings.AUTH_USER_MODEL, verbose_name='Update By')),
            ],
            options={
                'unique_together': {('name', 'port')},
            },
        ),
    ]
